export const SET_INGREDIENTS_LIST = 'SET_INGREDIENTS_LIST';
export const SET_SELECTED_LIST = 'SET_SELECTED_LIST';
export const SET_SALAD_TOTAL_PRICE = 'SET_SALAD_TOTAL_PRICE';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';